version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-app
    container_name: laravel-app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - laravel
    depends_on:
      - db
      - web

  web:
    image: nginx:latest
    container_name: laravel-web
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - laravel

  db:
    image: mysql:latest
    container_name: laravel-db
    restart: unless-stopped
    tty: true
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    platform: linux/amd64
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8082:80"
    depends_on:
      - db
    networks:
      - laravel

  rabbitmq:
    image: rabbitmq:3-management
    container_name: laravel-rabbitmq
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - 15672:15672
      - 5672:5672
    networks:
      - laravel
    depends_on:
      - app

  queue:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-queue
    container_name: laravel-queue
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: queue
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - laravel
    depends_on:
      - rabbitmq

  redis:
    image: redis:latest
    container_name: laravel-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - laravel
    depends_on:
      - app

volumes:
  dbdata:
    driver: local

networks:
  laravel:
    driver: bridge
